<?php

/**
 * PluginDmCommerceSupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceSupplierTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceSupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceSupplier');
    }
}