<?php

/**
 * PluginDmComProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProduct');
    }
}