<?php

/**
 * PluginDmCommerceCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceCategory');
    }
}