<?php

/**
 * PluginDmComProductTypeProductCharTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductTypeProductCharTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductTypeProductCharTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductTypeProductCharType');
    }
}