<?php

/**
 * PluginDmComProductDeclinationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductDeclinationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductDeclinationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductDeclination');
    }
}