<?php

/**
 * PluginDmCommerceCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceCountryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceCountry');
    }
}