<?php

/**
 * PluginDmCommerceManufacturerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceManufacturerTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceManufacturerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceManufacturer');
    }
}