<?php

/**
 * PluginDmComSupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComSupplierTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComSupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComSupplier');
    }
}