<?php

/**
 * PluginDmCommerceBuildingFloorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceBuildingFloorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceBuildingFloorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceBuildingFloor');
    }
}