<?php

/**
 * PluginDmComProductCharTypePropertyTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductCharTypePropertyTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductCharTypePropertyTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductCharTypePropertyType');
    }
}