<?php

/**
 * PluginDmCommerceSupplierProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceSupplierProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceSupplierProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceSupplierProduct');
    }
}