<?php

/**
 * PluginDmComAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComAddressTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComAddress');
    }
}