<?php

/**
 * PluginDmCommerceCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceCityTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceCity');
    }
}