<?php

/**
 * PluginDmComProductCharTypePropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductCharTypePropertyTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductCharTypePropertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductCharTypeProperty');
    }
}