<?php

/**
 * PluginDmComStreetTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComStreetTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComStreetTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComStreetType');
    }
}