<?php

/**
 * PluginDmCommerceStreetTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceStreetTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceStreetTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceStreetType');
    }
}