<?php

/**
 * PluginDmComCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComCategory');
    }
}