<?php

/**
 * PluginDmComProductTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductType');
    }
}