<?php

/**
 * PluginDmCommerceProductTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceProductTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceProductTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceProductType');
    }
}