<?php

/**
 * PluginDmComManufacturerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComManufacturerTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComManufacturerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComManufacturer');
    }
}