<?php

/**
 * PluginDmComCategoryProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComCategoryProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComCategoryProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComCategoryProduct');
    }
}