<?php

/**
 * PluginDmCommerceCategoryProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceCategoryProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceCategoryProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceCategoryProduct');
    }
}