<?php

/**
 * PluginDmComBuildingFloorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComBuildingFloorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComBuildingFloorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComBuildingFloor');
    }
}