<?php

/**
 * PluginDmCommerceProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceProduct');
    }
}