<?php

/**
 * PluginDmComCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComCityTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComCity');
    }
}