<?php

/**
 * PluginDmComProductCharTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductCharTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductCharTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductCharType');
    }
}