<?php

/**
 * PluginDmCommerceAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmCommerceAddressTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmCommerceAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmCommerceAddress');
    }
}