<?php

/**
 * PluginDmComSupplierProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComSupplierProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComSupplierProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComSupplierProduct');
    }
}